### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-axelar#6]
Before the submission to Ledger, we would need Axelar to provide the following:

**Submission checklist**

- [ ] 2 Icons (for Ledger device and Ledger Manager)  .ai (vector files) 
- [ ] Webwallet support
- [ ] Contact information (this is part of) 
- [ ] Link to tutorial hosted on third party website
- [ ] Brief video of your application running on the Ledger device
